// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlmemsesjpwtpxaznikg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbWVtc2VzanB3dHB4YXpuaWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODQ5NjQsImV4cCI6MjA2NTM2MDk2NH0.LvDOrTH6R-Sr0qbRjmvA_ExH3_DSDXcJ8fTR3Bis0Ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);